"""Proves every behaviour the A2A page claims about the refunds agent (in process, no network).

The raw client talks plain JSON-RPC to the official a2a-sdk server, so these tests also
check that the wire shapes shown on the page are what a real A2A 1.0 server accepts.
"""

import json

import anyio
import httpx
import pytest
import raw_client as rc
from app import app


@pytest.fixture
def anyio_backend():
    return "asyncio"


@pytest.fixture
async def http():
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app), base_url="http://agent") as client:
        yield client


async def rpc(http, method: str, params: dict, headers=rc.HEADERS) -> dict:
    body = {"jsonrpc": "2.0", "id": 7, "method": method, "params": params}
    return (await http.post("/a2a", json=body, headers=headers)).json()


@pytest.mark.anyio
async def test_card_is_served_at_the_well_known_path_in_camel_case(http):
    card = await rc.fetch_card(http)
    assert card["name"] == "Refund Status Agent"
    assert card["supportedInterfaces"][0] == {
        "url": "https://refunds.example.com/a2a",
        "protocolBinding": "JSONRPC",
        "protocolVersion": "1.0",
    }
    assert card["capabilities"] == {"streaming": True, "pushNotifications": False}
    assert card["skills"][0]["id"] == "refund-status"


@pytest.mark.anyio
async def test_missing_order_pauses_the_task_in_input_required(http):
    task = (await rc.send(http, "Where is my refund?"))["result"]["task"]
    assert task["status"]["state"] == "TASK_STATE_INPUT_REQUIRED"
    assert task["status"]["message"]["role"] == "ROLE_AGENT"
    assert task["status"]["message"]["parts"] == [{"text": "Which order ID?"}]
    assert task["id"] and task["contextId"]  # both generated by the server


@pytest.mark.anyio
async def test_follow_up_with_same_task_completes_it_with_a_data_artifact(http):
    task = (await rc.send(http, "Where is my refund?"))["result"]["task"]
    done = (await rc.send(http, "It is ORD-1234", task=task))["result"]["task"]
    assert done["id"] == task["id"]
    assert done["contextId"] == task["contextId"]
    assert done["status"]["state"] == "TASK_STATE_COMPLETED"
    [artifact] = done["artifacts"]
    assert artifact["name"] == "refund-status"
    assert artifact["parts"] == [{"data": {"order": "ORD-1234", "refund": "processed"}}]


@pytest.mark.anyio
async def test_blocking_send_returns_the_finished_task_in_one_call(http):
    task = (await rc.send(http, "Status of ORD-5678?"))["result"]["task"]
    assert task["status"]["state"] == "TASK_STATE_COMPLETED"
    assert task["artifacts"][0]["parts"][0]["data"]["refund"] == "pending"


@pytest.mark.anyio
async def test_stream_sends_task_first_then_updates_and_ends_at_terminal_state(http):
    body = {
        "jsonrpc": "2.0",
        "id": 9,
        "method": "SendStreamingMessage",
        "params": {
            "message": {"messageId": "m-1", "role": "ROLE_USER", "parts": [{"text": "ORD-5678 please"}]}
        },
    }
    resp = await http.post("/a2a", json=body, headers=rc.HEADERS)
    assert resp.headers["content-type"].startswith("text/event-stream")
    events = [json.loads(line[6:])["result"] for line in resp.text.splitlines() if line.startswith("data: ")]
    assert list(events[0]) == ["task"]
    assert list(events[1]) == ["artifactUpdate"]
    assert list(events[-1]) == ["statusUpdate"]
    assert events[-1]["statusUpdate"]["status"]["state"] == "TASK_STATE_COMPLETED"


@pytest.mark.anyio
async def test_missing_version_header_means_0_3_and_a_1_0_only_agent_rejects_it(http):
    params = {"message": {"messageId": "m-2", "role": "ROLE_USER", "parts": [{"text": "hi"}]}}
    error = (await rpc(http, "SendMessage", params, headers={}))["error"]
    assert error["code"] == -32009  # VersionNotSupportedError
    assert "'0.3'" in error["message"]


@pytest.mark.anyio
async def test_unknown_task_is_minus_32001(http):
    assert (await rpc(http, "GetTask", {"id": "no-such-task"}))["error"]["code"] == -32001


@pytest.mark.anyio
async def test_push_config_without_the_capability_is_minus_32003(http):
    task = (await rc.send(http, "Where is my refund?"))["result"]["task"]
    params = {"taskId": task["id"], "url": "https://client.example.com/hook"}
    assert (await rpc(http, "CreateTaskPushNotificationConfig", params))["error"]["code"] == -32003


@pytest.mark.anyio
async def test_list_tasks_omits_artifacts_and_ends_with_empty_page_token(http):
    await rc.send(http, "Status of ORD-1234?")
    result = (await rpc(http, "ListTasks", {}))["result"]
    assert result["nextPageToken"] == ""
    assert all("artifacts" not in t for t in result["tasks"])


# --- Where a2a-sdk 1.1.5 differs from the spec (the page's "spec vs SDK" table) ---


@pytest.mark.anyio
async def test_sdk_rejects_a_message_to_a_completed_task_but_with_minus_32602(http):
    task = (await rc.send(http, "Status of ORD-1234?"))["result"]["task"]
    error = (await rc.send(http, "and again", task=task))["error"]
    assert error["code"] == -32602  # the spec names UnsupportedOperationError (-32004)


@pytest.mark.anyio
async def test_sdk_accepts_a_context_id_that_does_not_match_the_task(http):
    task = (await rc.send(http, "Where is my refund?"))["result"]["task"]
    message = {
        "messageId": "m-3",
        "role": "ROLE_USER",
        "taskId": task["id"],
        "contextId": "some-other-context",
        "parts": [{"text": "ORD-1234"}],
    }
    reply = await rpc(http, "SendMessage", {"message": message})
    assert "error" not in reply  # the spec says agents MUST reject this
    assert reply["result"]["task"]["status"]["state"] == "TASK_STATE_COMPLETED"


@pytest.mark.anyio
async def test_cancel_on_a_settled_completed_task_is_minus_32002(http):
    task = (await rc.send(http, "Status of ORD-1234?"))["result"]["task"]
    await anyio.sleep(0.05)  # a cancel racing the completion can still see the finishing task
    reply = await rpc(http, "CancelTask", {"id": task["id"]})
    assert reply["error"]["code"] == -32002  # TaskNotCancelableError, as the spec says


@pytest.mark.anyio
async def test_legacy_0_3_method_name_is_method_not_found(http):
    params = {"message": {"messageId": "m-4", "role": "user", "parts": [{"kind": "text", "text": "hi"}]}}
    for headers in ({}, rc.HEADERS):
        assert (await rpc(http, "message/send", params, headers=headers))["error"]["code"] == -32601


@pytest.mark.anyio
async def test_cancel_moves_a_paused_task_to_canceled(http):
    task = (await rc.send(http, "Where is my refund?"))["result"]["task"]
    reply = await rpc(http, "CancelTask", {"id": task["id"]})
    assert reply["result"]["status"]["state"] == "TASK_STATE_CANCELED"
